### ISSUE TITLE
Abs. 2009.3 TB-3: testing and correcting

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#239]

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

p213 und die Weiterleitung dort hinaus passen jetzt 👍

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 

Ich habe nun die restlichen Schleifen programmiert. Für heute bin ich nun leer im Kopf. 

https://media.giphy.com/media/KlR8SZupKObf2/giphy.gif

Wenn du magst, kannst du aber schon mal anfangen zu checken.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski  

Super 🥇 , dann fang ich mal an - aber erstmal niedrigschwellig mit Rechtschreibung etc. ;-)

**Comment by SilinaKowalewski** [comment]
> - [ ]  Auf p206/p306/p406/p506/p606/p706 sitzt der Text bei v93k1-6ezstz und v93k1-6ezptz (jeweils it3) zu tief und nicht bündig mit dem Mehrfachsauswahl- und Eingabefeld

@vdick kannst du dir das Problem bitte mal anschauen?

**Comment by thorsteneuler** [comment]
Bitte die Zeitangabe auf der index-Seite "ca. xx bis xx Minuten in Anspruch" durch "durchschnittlich ca. 5 bis 15 Minuten in Anspruch" ersetzen.

**Comment by thorsteneuler** [comment]
Bitte Abgangsfilter für p105 überprüfen. Ich komme bei v93kinder=3 nicht von p105 runter. Weder mit v93partner=1 (-> GOTO p901), noch v93partner<>1 (-> GOTO p990)

**Comment by SilinaKowalewski** [comment]
> Bitte Abgangsfilter für p105 überprüfen. Ich komme bei v93kinder=3 nicht von p105 runter. Weder mit v93partner=1 (-> GOTO p901), noch v93partner<>1 (-> GOTO p990)

@thorsteneuler: 
Bei mir funktioniert der Filter. Sieht soweit auch richtig programmiert aus. 

Mit dem Unterschied, dass laut PV im Falle von v93kinder=3  und v93partner<>1 --> GOTO p920. 
Ist das so richtig?

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Ja, p920 ist richtig. Ich komme mit tester13 aber dennoch nicht von p105 weiter.

**Comment by SilinaKowalewski** [comment]
Ah, Fehler gefunden. Rolle ich gleich neu aus!

**Comment by thorsteneuler** [comment]
> 
> 
> Ah, Fehler gefunden. Rolle ich gleich neu aus!

Läuft jetzt 👍

**Comment by vdick** [comment]
Auf p206/p306/p406/p506/p606/p706 sitzt der Text bei v93k1-6ezstz und v93k1-6ezptz (jeweils it3) zu tief und nicht bündig mit dem Mehrfachsauswahl- und Eingabefeld
 
@SilinaKowalewski  fixed und commited

**Comment by thorsteneuler** [comment]
- [ ] Bitte die Transition auf p207 so einstellen, dass 
GOTO p207a IF ((v93k1leisp=value AND v93k1leipp=value AND v93k1part!=2) OR (v93k1leisp=value AND v93k1part<>2)
 -> d.h. entweder haben beide Elterngeldplus genommen oder die/der Alleinerziehende (waren bislang untergegangen) hat Elterngeldplus gehabt

- [ ] Bei p212 bitte die ao erweitern (einige Sonderfälle könnten dort landen und nicht abgedeckt sein)
ao1: 1 :  : habe so lange unterbrochen wie von mir gewünscht.
ao2: 2 :  : hätte gerne länger unterbrochen.
ao3: 3 :  : hätte gerne kürzer unterbrochen.
ao4: 4 :  : wollte nicht unterbrechen.
ao5: 5:   : habe nicht unterbrochen/trifft nicht zu
ao6: 6 :  : Sonstiges: [string]

- [ ] Die Änderungen für p307-707 bzw. p312-712 bitte ebenso durchführen

**Comment by kastirke** [comment]
@SilinaKowalewski Hier kommt die PV für die neuen SAS/ATS-Items im Änderungen verfolgen-Modus (Basis: Abs2009.3_PV_TB3_011-1.docx). Relevant sind lediglich p906 bis 923. Rückfragen bitte an mich.
@thorsteneuler Bitte gern prüfen und eure PV entsprechend aktualisieren.

[Abs2009.3_PV_TB3_011-1_240919_ats.docx](https://github.com/dzhw/zofar/files/3645848/Abs2009.3_PV_TB3_011-1_240919_ats.docx)

**Comment by thorsteneuler** [comment]
@kastirke Danke, ich habe noch ein paar Anpassungsbedarfe gefunden, da man nicht nur von p906 auf p920 kommt und die s_split_sas schon früher kommen muss. Bitte nochmal prüfen auf den Seiten p105-p107.

@SilinaKowalewski Habe die notwendigen Umstellungen (Erstellen der s_split_sas1=1 bereits auf p105, Ergänzung der transitions auf p105-p107) in Nadins PV eingebaut.

[Abs2009.3_PV_TB3_011-1_240919_ats_te.docx](https://github.com/dzhw/zofar/files/3645905/Abs2009.3_PV_TB3_011-1_240919_ats_te.docx)

**Comment by thorsteneuler** [comment]
> 
> 
> Auf p206/p306/p406/p506/p606/p706 sitzt der Text bei v93k1-6ezstz und v93k1-6ezptz (jeweils it3) zu tief und nicht bündig mit dem Mehrfachsauswahl- und Eingabefeld
> 
> @SilinaKowalewski fixed und commited

Wurde das schon neu ausgerollt? Bei meinen aktuellen beiden Versuchen (verschiedene Browser) sitzt der Text auf p206 immer noch in den Kniekehlen.

**Comment by kastirke** [comment]
@thorsteneuler Danke für die Ergänzung zu p105-p107. Das ist korrekt. Habe aber auf p906 von s_split_sas**1** zu s_split_sas**2** geändert, um jeweils neu zu Randomisieren und keine Pfadabhängigkeit herzustellen.

Hier ist die aktualisierte PV: 
[Abs2009.3_PV_TB3_011-1_240919_ats_te_nk.docx](https://github.com/dzhw/zofar/files/3646027/Abs2009.3_PV_TB3_011-1_240919_ats_te_nk.docx)

**Comment by kastirke** [comment]
@thorsteneuler: we have to shortened the word length for our Test; see #249). 

- p922 und p923: "Ergebnisse von Umfragen" instead of "Umfrageergebnisse"
- p922 und p923: "Teilnehmenden" instead of "Umfrageteilnehmenden"

Is that okay for you?

**Comment by thorsteneuler** [comment]
@kastirke 

No objection from my side.

**Comment by kastirke** [comment]
@SilinaKowalewski Let's go. Please start programming the changes.
[Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx](https://github.com/dzhw/zofar/files/3646754/Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx)

**Comment by SilinaKowalewski** [comment]
Alle Änderungen sind umgesetzt und einmal grob getestet. 

Auf einigen Seiten habe ich die Steuerungsvariablen unten eingeblendet.

**Comment by kastirke** [comment]
@SilinaKowalewski Thanks. May you provide a link to the survey? Am I allowed to test with any testerX?

**Comment by thorsteneuler** [comment]
@kastirke 

You can take any of tester90-tester99

**Comment by kastirke** [comment]
@SilinaKowalewski Thanks.

- [ ] Drop variables s_split_sas2 and s_split_ats2 (if the sv are generated when leaving the index page, we don't need them)
- [ ] change within the tr on p906 from s_split_sas2 into s_split_sas1
- [ ] change within the tr on p921 from s_split_ats2 into s_split_ats1

Here is the updated PV: 
[Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx](https://github.com/dzhw/zofar/files/3647852/Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx)

**Comment by kastirke** [comment]
When leaving p107:
![grafik](https://user-images.githubusercontent.com/30147532/65524155-a0543780-deed-11e9-82c3-1ef4da14438c.png)

**Comment by thorsteneuler** [comment]
- [ ] Auf p922 und p923 bitte den zweiten Punkt (..) am Ende von it6 entfernen
- [ ] Auf p922 und p923 bitte hinter it9 einen Punkt (.) hinzufügen
- [ ] Auf p921 bitte den zweiten Punkt (..) am Ende von it12 entfernen

**Comment by kastirke** [comment]
I will continue testing when the above mentioned changes are done.

**Comment by kastirke** [comment]
Little text changes due to input from Uli S.

- [ ] auf p922/p923/it4 from "passieren wird" to "später passiert"
- [ ] auf p922/p923/it7 from "Ich glaube, die Ergebnisse von Umfragen werden in der Regel stark von den persönlichen Interessen der Akteure beeinflusst, die die Umfrage durchführen." to "Ich bin der Meinung, dass die Ergebnisse von Umfragen in der Regel stark von den persönlichen Interessen der Akteure beeinflusst werden, die die Umfrage durchführen."
- [ ] auf p922/p923/it9 from "Ich habe den Eindruck, dass Umfragen immer so gestaltet werden, das die erwünschten Ergebnisse rauskommen." to "Ich habe den Eindruck, dass Umfragen immer so gestaltet sind, das letztlich die gewünschten Ergebnisse herauskommen."

[Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx](https://github.com/dzhw/zofar/files/3648278/Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx)

**Comment by thorsteneuler** [comment]
> 
> 
>     * [ ]  Bitte die Transition auf p207 so einstellen, dass
>       GOTO p207a IF ((v93k1leisp=value AND v93k1leipp=value AND v93k1part!=2) OR (v93k1leisp=value AND v93k1part<>2)
>       -> d.h. entweder haben beide Elterngeldplus genommen oder die/der Alleinerziehende (waren bislang untergegangen) hat Elterngeldplus gehabt
>       @thorsteneuler: Habe die Änderungen für die Frage p207 umgesetzt. Bitte prüf einmal ob dies so passt bevor ich die Änderungen in die weiteren Seiten einpflege.
> 
>    

@SilinaKowalewski 
Sehe gerade, dass es "(v93k1leisp=value AND v93k1part=2)" heißen muss - mein Fehler. Bitte ändere das für die p207, dann prüfe ich das nochmal und gebe dir dann das Okay fürs Kopieren in die anderen Schleifen.

**Comment by thorsteneuler** [comment]
https://github.com/dzhw/zofar/issues/239#issuecomment-534602536

Der Seitenfehler von Nadin auf p107 passiert, wenn v93partner!=1 ist (bei =1 kommt man planmäßig auf die p901). Vielleicht hilft's bei der Fehlersuche.

**Comment by thorsteneuler** [comment]
- [ ] Bitte die transition von p211 prüfen:
GOTO p218 IF v93kzahl>1 AND v93k1ezpeu<>1 -> Soll auf p218 leiten wenn mehr als 1 Kind und v93k1ezpeu nicht ausgewählt wurde (entweder weil der Partner keine Erwerbsunterbrechung hatte oder es keinen Partner gab).
Alternativ müsste auch folgendes funktionieren: GOTO p218 IF v93kzahl>1 AND (v93k1ezpeu!=value OR v93k1part!=1)

**Comment by SilinaKowalewski** [comment]
@thorsteneuler @kastirke:

Alle Änderungen umgesetzt. Bitte prüft einmal ob alles richtig umgesetzt ist.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Die Transitions von p107 auf p920/p921 funktioniert nun bei Partnerlosen, ebenso der Abgang von p211. 
Die Transition von p207 auf p207a für den Fall v93k1part=2 [keine Partnerschaft bei Geburt] in Kombination von p93k1leisp=value [Person(Ego) hat ElterngeldPlus auf p207 angekreuzt] funktioniert noch nicht. Anstatt auf p207a lande ich auf p208 (was aufgrund von <zofar:transition target="p208" condition="v93k1leisp.value or v93k1leipp.value"/> nur die Fälle abdecken soll, bei denen in einer Partnerschaft nur eine Person ElterngeldPlus bezog, Paare mit doppeltem ElterngeldPlus-Bezug oder Alleinerziehende mit ElterngeldPlus-Bezug sollen vorher auf p207a).  

btw: Gibt es eigentlich einen Link, mit dem ich den Survey von außerhalb des DZHW auf dem Smartphone testen kann?

**Comment by SilinaKowalewski** [comment]
Ah, Tippfehler gefunden. Schau nochmal ob es nun klappt. Die Bedingungen sehen aber an sich richtig aus. 

Über den bekannten Link solltest du auch mit dem Smartphone testen können.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 
Nein, klappt immer noch nicht. Komme als Person ohne Partnerschaft bei Geburt (v93k1part=2) auf p202 und ausgewähltem Elterngeldplus für mich (v93k1leisp=Häkchen) nicht auf p207a.

Mailst du mir nochmal die aktuelle Transitionprogrammierung von p207, dann schaue ich nochmal drauf? Vielleicht ist da irgendwo noch ein Dreher drin.

**Comment by SilinaKowalewski** [comment]
<zofar:transitions>
			<zofar:transition target="p207a" condition="(v93k1leisp.value and v93k1leipp.value and zofar.asNumber(v93k1part)!=2) or (v93k1leipp.value and zofar.asNumber(v93k1part)==2)"/>
			<zofar:transition target="p208" condition="v93k1leisp.value or v93k1leipp.value"/>
			<zofar:transition target="p209" condition="v93k1ezsku.value or v93k1ezpku.value"/>
			<zofar:transition target="p212" />
		</zofar:transitions>

**Comment by thorsteneuler** [comment]
"(v93k1leisp.value and v93k1leipp.value and zofar.asNumber(v93k1part)!=2) or (v93k1leisp.value and zofar.asNumber(v93k1part)==2)"

Hinter dem OR stand v93k1leipp.value, muss aber v93k1leisp.value heißen.

**Comment by SilinaKowalewski** [comment]
Ouh, dass ist völlig durch die Lappen gegangen. Habe es geändert und rolle nun neu aus. 
Danke für deine Hilfe!

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Bitte :-) Roll neu aus, dann checke ich's nochmal.

**Comment by thorsteneuler** [comment]
Bitte die Seite "offer" für die Nutzer mit Smartfon überprüfen. Ich bin von dieser gerade direkt auf "end" weitergeleitet worden anstatt auf p101.

**Comment by kastirke** [comment]
@SilinaKowalewski 

- [ ] Auf p922 soll das alte Design (Matrix bricht bei kleinen Endgeräten nicht um in Carousel) umgesetzt werden. Siehe #249 Bitte Christian fragen, wie die Responsivität für dieser einen Seite deaktiviert wird.
- [ ] p922 & p923: Bitte alle Items rotieren lassen (randomisiert wechselnde Reihenfolge)
- [ ] auf p922/it4 & p23/it4 from "später passieren wird" to "später passiert"
- [ ] auf p906 stimmt was nicht mit der tr: habe **Wert "s_split_sas1": 2** und werde auf p920 statt p921 geleitet
- [ ] : Ist es möglich, auf p921 it10-it12 rotieren zu lassen, also in wechselnder Reihenfole zu präsentieren (it1-it9 aber in der vorgegebenen Reihenfolge)?  Falls nicht, dann bitte alle Items rotieren lassen.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Die Transition von 207 auf p207a für Alleinerziehende mit ElterngeldPlus-Bezug klappt jetzt. Kann auf die anderen p*07-Seiten kopiert werden.

- [ ] Bei Benutzung vom Smartfon ist die Anzeige der Kombinationen Eingabefeld und Text auf p206 und p207 graphisch etwas zerschossen. (Siehe unten)
- [ ] Das Problem auf p206 mit dem zu tiefen Text bei it3 besteht immer noch: https://github.com/dzhw/zofar/issues/239#issuecomment-534091369 

- [ ] Die Weiterleitung von p802 auf p803 auf Basis von h_multikind klappt noch. Ich komme bei Auswahl zweier Optionen mit "Weiter" erst auf p804, wenn ich aber dann wieder zurück auf p802 gehe und erneut "Weiter" klicke, komme ich auf p803. 
- [ ] Bitte schau dir die h_multikind-Transition auf p802 an. Wenn es nicht in überschaubarer Zeit zu lösen ist, dann leiten wir alle Befragten von p802 auf immer p803 und blenden auf p803 immer ao1 [Ich selbst] ein und die anderen ao2-ao12 auf Basis der Auswahl der korrespondierenden Mehrfachantwort von Seite p802.

**Ansicht p206 auf Mobilgerät**

![p206](https://user-images.githubusercontent.com/52777773/65600584-aeaf5b80-dfa0-11e9-9dcb-7dd5b1852345.jpg)
 
**Ansicht p207 auf Mobilgerät**

![p207](https://user-images.githubusercontent.com/52777773/65600703-f1713380-dfa0-11e9-8113-c644a1e33a85.jpg)

**Comment by thorsteneuler** [comment]
- [ ] Auf Seite p803 greift die Eingabebeschränkung (siehe unten) nicht.
av: number: ≤ dreistellig: 0 TO 168
kh: Bitte geben Sie eine Zahl zwischen 1 und 168 ein (Stunden/Woche).

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 
Die Weiterleitung von der Seite p802 sollte nun passen. Habe hierfür allerdings nicht die Hilfsvariable genutzt. Ihr wollte diese Hilfsvariable aber vermutlich dennoch im Datensatz haben oder war diese lediglich zur Steuerung gedacht?

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 
Die Hilfsvariable ist nur zur Steuerung gedacht falls mehr als eine Option auf p802 ausgewählt wird. Im Datensatz benötigen wir sie nicht, da jeder Nutzer solch eine Zählvariable aus den p802-Antworten selbst erstellen kann. Die Hilfsvariable ist m.M. ohnehin mit Vorsicht zu genießen, da die Hilfsvariable aus unserer ersten Teilbefragung zwar korrekt gesteuert hat (anders als bei Abs2013.2), aber die abgespeicherten Werte nicht immer korrekt waren.
Wenn die Weiterleitung von p802 auch ohne die Hilfsvariable funktioniert, umso besser.

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: Ah, verdammt. Habe falsch gedacht. Die Transition läuft doch nicht :(

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Versuch's mal mit dieser beigefügten Variante. Das ist die ausführliche Version mit allen Kombinationen, die nicht auf p803 führen (13 Stück) - aber ohne Hilfsvariable.
[p802_transitions_ohne_hilfsvariable.docx](https://github.com/dzhw/zofar/files/3653451/p802_transitions_ohne_hilfsvariable.docx)

**Comment by SilinaKowalewski** [comment]
Danke für deine großartige Zuarbeit!! 🥇 

Nach einem kurzen Test würde ich sagen, dass es gut funktioniert. Habe es aber direkt ausgerollt damit du auch prüfen kannst.

**Comment by thorsteneuler** [comment]
Bitte bei p217 in der Transition alle "v93kzahl=1" durch "(v93kzahl=1 or v93kzahl=SYSMISS)" ersetzen (betrifft die tr auf p801, p802, p901 und p990). Es sollte zwar wenige Personen geben, die bei der Kinderzahl keine Angabe machen, aber die würden bislang auf p217 sonst festhängen. Betrifft nur p217, nicht die anderen Schleifen.

**Comment by thorsteneuler** [comment]
> 
> 
> Danke für deine großartige Zuarbeit!! 🥇
> 
> Nach einem kurzen Test würde ich sagen, dass es gut funktioniert. Habe es aber direkt ausgerollt damit du auch prüfen kannst.

@SilinaKowalewski 
Passt, das Problem ist gelöst und die Hilfsvariable ist keine BlackBox mehr. 👍

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 
- [ ] Auf p211 bei den transitions bitte checken, ob überall das v93k1ezpeu<>1 zur Leitung auf p218, p801, p802, p901 und p990 richtig gesetzt ist, also "!v93k1ezpeu.value". Habe beim Testen eine Kombi gehabt, die auf p901 führen sollte, jedoch kam ich von p217 nicht runter.

Kannst mir auch gerne die transition hier kurz einblenden, dann schaue ich auch mal.

**Comment by SilinaKowalewski** [comment]
> > Danke für deine großartige Zuarbeit!! 🥇
> > Nach einem kurzen Test würde ich sagen, dass es gut funktioniert. Habe es aber direkt ausgerollt damit du auch prüfen kannst.
> 
> @SilinaKowalewski
> Passt, das Problem ist gelöst und die Hilfsvariable ist keine BlackBox mehr. 👍

Die Hilfsvariable lösche ich dann komplett, richtig?

**Comment by kastirke** [comment]
@SilinaKowalewski & @thorsteneuler Soll/Muss der Hinweis auch kommen, wenn die Matrix nicht umbricht in ein Carousel?
![grafik](https://user-images.githubusercontent.com/30147532/65673284-d65afe00-e04a-11e9-9cf4-24724c067a8b.png)

**Comment by thorsteneuler** [comment]
> 
> 
> > > Danke für deine großartige Zuarbeit!! 🥇
> > > Nach einem kurzen Test würde ich sagen, dass es gut funktioniert. Habe es aber direkt ausgerollt damit du auch prüfen kannst.
> > 
> > 
> > @SilinaKowalewski
> > Passt, das Problem ist gelöst und die Hilfsvariable ist keine BlackBox mehr. 👍
> 
> Die Hilfsvariable lösche ich dann komplett, richtig?

Ja, die Hilfsvariable h_multikind kann komplett gelöscht werden.

**Comment by kastirke** [comment]
@SilinaKowalewski 

- [ ] p922 & p923: Entfernen des Hinweises "Diese Seite enthält...wechsen." und Checkbox (Hintergrund: auf p922 soll Matrix nicht umbrechen und auf p923 soll die neue Version mit automatic forwarding umgesetzt werden)
"Falls im responsiven Design aus den Items ein Itemkarussell wird, sofern technisch möglich bei Auswahl einer ao automatisch auf das nächste Item des Karussells weiterleiten. Ansonsten bitte einen Hinweis als is einblenden „mit den Pfeiltasten kommen Sie zur nächsten Teilfrage“. Alternativ falls it1 <> SYSMISS und it2-it(n) =  SYSMISS soft_force Hinweis „Diese Seite enthält Teilfragen. Mit den Pfeiltasten können Sie zwischen diesen wechseln.“ einbauen. Bei Rückfragen bitte melden." wurde aus der PV gelöscht

[Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx](https://github.com/dzhw/zofar/files/3656871/Abs2009.3_PV_TB3_011-1_240919_ats_programmed.docx)

**Comment by kastirke** [comment]
@SilinaKowalewski & @dzhwmeisner 

- [ ] auf p923 bitte das neue Carousel mit automatic forwarding umsetzen (#249)

**Comment by thorsteneuler** [comment]
@kastirke  https://github.com/dzhw/zofar/issues/239#issuecomment-535405370 

Nein, der Hinweis soll natürlich nicht bei einer normalen Matrixanzeige kommen. Ich habe ihn eben nicht erhalten, weiß aber, dass er gestern unregelmäßig auftauchte wenn ich auf den Seiten vor- und zurücksprang.

**Comment by SilinaKowalewski** [comment]
@kastirke @thorsteneuler: 

Habe den Hinweis nun auf den Seiten p920, p921, p922 und p923 raus genommen.

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: Ob der Hinweistext angezeigt wird, ist/war bereits abhängig von Endgerät. Durch die Einschränkung "width.value lt 768" wird der Hinweis also erst unter einer bestimmten Breite angezeigt. 

Der Fall, dass der Hinweistext auftritt aber die Matrix nicht umbricht kann demnach eigentlich nicht eintreten. Es sei denn ihr testen über die Entwicklertools im Browser das responsive Design. 

Werde aber nun die Hinweise auf p920 und p921 wieder einbauen.

**Comment by vdick** [comment]
@SilinaKowalewski 
p206/p306/p406/p506/p606/p706
p207/p307/p407/p507/p607/p707
optimiert

**Comment by vdick** [comment]
@SilinaKowalewski 
p921/p922 unit fixed

**Comment by thorsteneuler** [comment]
Von Projektseite gibt es keinen bekannten weiteren Änderungsbedarf (irgendwelche Kombinationen haben wir bestimmt vergessen, aber die treten hoffentlich nie ein).

Von unserer Seite aus können also Lasttest und Datacheck über die Bühne gehen.

**Comment by SilinaKowalewski** [comment]
Addon kann nun mit den bekannten Token getestet werden: 

https://presentation.dzhw.eu/abs20093tb3-addon

**Comment by thorsteneuler** [comment]
> 
> 
> @vdick: Kannst du bitte die Textfelder in der Addon-Befragung deutlich größer machen? Über das QML lässt sich an der Größe nichts ändern :(

Das wäre auch meine Bitte gewesen. Und bitte die Präfixe nicht am oberen Rand, sondern mittig ausrichten wie bei diesem Screenshot von Abs2013.2-TB3:

![Addon-Variante-1_Browser](https://user-images.githubusercontent.com/52777773/65887261-f158a580-e39d-11e9-8a84-044b8c98809c.png)

**Comment by vdick** [comment]
@SilinaKowalewski  habe gerade alles angepasst, bitte neu ausrollen

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Dank des datacheck ist nun noch aufgetaucht, dass Befragte mit verweigerter Zahlenangabe bei der Kinderzahl bei den Ausstiegen der ersten Kinderschleife auf den Seiten p203, p211, p213 und p216 hängenbleiben können.

Bei allen vier Seiten muss in den Transitions auf p801, p802, p901 und p990 bei den conditions das jeweils ganz vorne stehende **zofar.asNumber(v93kzahl)==1** durch **(zofar.asNumber(v93kzahl)==1 or zofar.isMissing(v93kzahl))** ersetzt werden. Die Kinderzahl entspricht als 1 oder fehlt, dann kommt man je nach Restbedingung auf p801, p802, p901 oder p990. 

Es dürften zwar wenige Befragte die Zahlenangabe verweigern, aber denkbar ist es noch.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Ich hab doch noch was gefunden - verdammt. Auf p105 ist die Visibilty der Questions falsch.

  <zofar:page uid="p105">
		<zofar:body uid="b">
			<zofar:questionSingleChoice uid="sc">
				<zofar:header>
					<zofar:question uid="q1" block="true" visible="zofar.asNumber(v93kzahl)==1">
						Alles in allem, wie können Sie zurzeit Beruf und Familie miteinander vereinbaren?
					</zofar:question>
					<zofar:question uid="q2" block="true" visible="zofar.asNumber(v93kzahl)!=1 and zofar.asNumber(v93partner)==1">
						Alles in allem, wie können Sie zurzeit Beruf und Partnerschaft miteinander vereinbaren?
					</zofar:question>
					<zofar:question uid="q3" block="true" visible="zofar.asNumber(v93kzahl)!=1 and zofar.asNumber(v93partner)!=1">
						Alles in allem, wie können Sie zurzeit Beruf und Privatleben miteinander vereinbaren?
					</zofar:question>
				</zofar:header>


**Anstatt v93kzahl muss an allen drei Stellen v93kinder stehen.**

@vdick 
Könntest du das bitte noch vorm Ausrollen ändern, sprich die drei Variablennamen austauschen?

**Comment by SilinaKowalewski** [comment]
Es wurden alle Änderungen umgesetzt und die Befragung produktiv ausgerollt.
