### ISSUE TITLE
adjustment of color contrasts

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/zofar#425]
**Um zofar-Befragungen generell barrierearmer zu gestalten müssen an einigen Stellen die Text- oder Hintergrundfarben angepasst werden.** 

> Der Helligkeitsunterschied wird in einem Verhältnis von 1:1 (zum Beispiel weißer Text auf weißem Hintergrund) bis 21:1 (zum Beispiel schwarzer Text auf weißem Hintergrund) ausgedrückt.
> 
> Mindestwert für das Kontrastverhältnis zwischen Vorder- und Hintergrund = 4,5:1
_____

Diese Mindestwerte werden für folgende Darstellungen aktuell nicht eingehalten
- [ ] Counter-Text (aktuell 1,5:1) > ändern zu #757575 oder #006ab2 (entspricht DZHW-blau)
- [ ] Radio-Button und Checkboxen bzw. deren Rahmen (aktuell 1,39:1) > ändern zu #757575
- [ ] Infield-Text (aktuell 2,43:1) > ändern zu #757575

**Comment by vdick** [comment]
@SilinaSchirmer please create a new project via archetype to test

**Comment by christian-fr** [comment]
>     * [x]  Counter-Text (aktuell 1,5:1) > ändern zu #757575 oder #006ab2 (entspricht DZHW-blau)
>
>     * [x]  Radio-Button und Checkboxen bzw. deren Rahmen (aktuell 1,39:1) > ändern zu #757575
>
![grafik](https://user-images.githubusercontent.com/42959832/132505805-bd875098-dc19-421c-ac9f-83b8bd93414d.png)

![grafik](https://user-images.githubusercontent.com/42959832/132505859-a5e5a8b5-3f54-480d-be92-069d41866f69.png)

-> looks good to me, color #757575 can be confirmed

>     * [x]  Infield-Text (aktuell 2,43:1) > ändern zu #757575

-> could not test it yet because I was not able to implement infield texts @SilinaSchirmer could you take a look?

**Comment by SilinaSchirmer** [comment]
@vdick: Es sieht für mich so aus, als wären noch weitere Anpassungen notwendig. Melde dich einfach mal bei Gelegenheit damit ich dir erklären kann was ich meine.

**Comment by andreaschu** [comment]
@vdick und @SilinaSchirmer was ist hier der Status? Hat sich etwas getan?

**Comment by vdick** [comment]
@andreaschu bin gerade überfragt.. werde gleich mit Silina sprechen
